spring:
  application:
    name: smarkhis
  datasource:
    url: jdbc:postgresql://localhost:5432/smarkhis
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
jwt:
  secret: smarkhisv1

server:
  port: 8081

